### PR TITLE
LIIKUNTA-259 | Fix ontologies overlapping datetime picker

### PR DESCRIPTION
**Pull request by Jokinen**
## Description

Changes z-index so that date time picker isn't rendered below keywords.

### Closes

**[LIIKUNTA-259](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-259):**

## Screenshots

Screenshot 2022-01-10 at 14 04 17
Screenshot 2022-01-10 at 14 04 21

### CODE REVIEW

**Comment by Sartonon** [comment]
Having issues running this branch locally.

Screenshot 2022-01-12 at 17 20 56

**Comment by Sartonon** [comment]
Something going on with collections:

```
 graphQLErrors: [
    {
      debugMessage: 'Cannot return null for non-nullable field "Collection.id".',
      message: 'Internal server error',
      extensions: [Object],
      locations: [Array],
      path: [Array]
    }
  ],
```

**Review by Sartonon — APPROVED** [review]
Looks good but while trying to figure out why this has to be done or why keywords have high z-index I noticed that some event card look strange in venue page:

Screenshot 2022-01-13 at 9 36 53

**Comment by Jokinen** [comment]
They do look strange, but some of that is due to the data being a bit difficult to navigate. The amount of tags is limited to an amount that would look good when the keyword has a one/two word label.

**Comment by Jokinen** [comment]
I added a fix to the collection issue you mentioned.

**Pull request merged**
